apiVersion: apps/v1
kind: Deployment
metadata:
  name: anchore-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: anchore-operator
  template:
    metadata:
      labels:
        name: anchore-operator
    spec:
      serviceAccountName: anchore-operator
      containers:
        - name: anchore-operator
          # Replace this with the built image name
          image: docker.io/btodhunter/anchore-operator:latest
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "anchore-operator"
